# drone 本地构建
kind: pipeline
type: docker
name: note-deploy

# drone执行触发器
trigger:
  branch:
    - master

# drone构建步骤
steps:
  # 1.打成docker镜
  - name: docker-build
    pull: if-not-exists
    image: plugins/docker
    settings:
      repo: local-repo:5000/0moe-note
      # username: cn-east-3@OSLWAOUDJLI5YPEKRSS5
      # password: a01ac7aaf9e74d102d0a35f79391478c7ee95929b40daa27a0dc2be031f59745
      tags: 
        - latest
        - ${DRONE_COMMIT_SHA}
      dockerfile: conf/Dockerfile
  # 2.部署到k3s
  - name: k3s-deploy
    pull: if-not-exists
    image: vallard/drone-kube
    settings:
      namespace: dev
      template: /root/note.yml
  # 4.邮件通知
  - name: email-notice
    pull: if-not-exists
    image: drillster/drone-email
    settings:
      host: smtp.exmail.qq.com
      port: 465
      username: system@0moe.cn
      password: MjEcKARP3qAECSMS
      from: system@0moe.cn
    when:
      status: [failure, success]