# drone 本地构建
kind: pipeline
type: docker
name: note-deploy

# drone执行触发器
trigger:
  branch:
    - master

# drone构建步骤
steps:
  # 1.打成docke
  - name: docker-build
    pull: if-not-exists
    image: plugins/docker
    settings:
      registry: local-repo:5000
      insecure: true
      repo: local-repo:5000/0moe-note
      tags: 
        - latest
        - ${DRONE_COMMIT_SHA}
      dockerfile: conf/Dockerfile
  # 2.部署到k3s
  - name: k3s-deploy
    pull: if-not-exists
    image: vallard/drone-kube
    settings:
      server: http://172.17.0.6:6433
      token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkdfcEFaMHV3eVFVaWNaWUJkNGM2ZjljVUJCcnFaYW5xdTgza09MYXlnWkkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi11c2VyLXRva2VuLTRzYnpxIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImFkbWluLXVzZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI3MzEwN2E0YS1hOTMyLTQxYjQtODc5ZC1kMTk3NGIwNDBmODEiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZXJuZXRlcy1kYXNoYm9hcmQ6YWRtaW4tdXNlciJ9.dZk2XH8cB7seqi6FVdEkiu_5BeXiPMtCazJiNHERVXHvuCyZ2QobH44bp1ij3TD7_1of96jgZynk8KSpwkcvXSdQ66DxJyj8j8kHPFFUajwTL8kh98ZKyLk6lseo5xX2tDEaDFJb3t0hRgYkr6IDeDG2fECilsR8Fz9jW0pkh9PEN99cQN32TaFCIh5AtXtrnbal_Wacai-yBLHULA8p0Uumvb6hF_AIDTOW2zNVX2IgDIcDzLHX-z99Jz1lC6lPS0bnBc8R55O6Jkeow1R0AI6gnoC8iNboICtkQl-CTLD7j7xbIYYnp-8ljCDLWMxr1xgWbLjGKFoA3nUh7C1geA
      namespace: dev
      template: /root/note.yml
  # 4.邮件通知
  - name: email-notice
    pull: if-not-exists
    image: drillster/drone-email
    settings:
      host: smtp.exmail.qq.com
      port: 465
      username: system@0moe.cn
      password: MjEcKARP3qAECSMS
      from: system@0moe.cn
    when:
      status: [failure, success]