# drone 本地构建
kind: pipeline
type: kubernetes
name: note-deploy

# drone执行触发器
trigger:
  branch:
    - master
# 客制化clone
clone:
  disable: true

# drone构建步骤
steps:
  - name: clone
    image: curlimages/curl
    commands:
    - echo '140.82.114.4 github.com' >> /etc/hosts
    - curl https://github.com/$DRONE_REPO
    - git clone https://github.com/$DRONE_REPO
    - git checkout $DRONE_COMMIT
  # 1.打成docker镜
  - name: docker-build
    pull: if-not-exists
    image: plugins/docker
    settings:
      repo: 0moe
      tags: 
        - latest
        - sha_${DRONE_COMMIT_SHA}
      dockerfile: conf/Dockerfile
  # 3.部署到k3s
  - name: k3s-deploy
    pull: if-not-exists
    image: vallard/drone-kube
    settings:
      namespace: dev
      template: /root/note.yml
  # 4.邮件通知
  - name: email-notice
    pull: if-not-exists
    image: drillster/drone-email
    settings:
      host: smtp.exmail.qq.com
      port: 465
      username: system@0moe.cn
      password: MjEcKARP3qAECSMS
      from: system@0moe.cn
    when:
      status: [failure, success]