# drone 本地构建
kind: pipeline
type: docker
name: note-deploy

# drone执行触发器
trigger:
  branch:
    - master

volumes:
  - name: cache
    host:
      path: /root

# drone构建步骤
steps:
  # 1.打成docke
  - name: docker-build
    pull: if-not-exists
    image: plugins/docker
    settings:
      registry: local-repo:5000
      insecure: true
      repo: local-repo:5000/0moe-note
      tags: 
        - latest
        - ${DRONE_COMMIT_SHA}
      dockerfile: conf/Dockerfile
  # 2.部署到k3s
  - name: ssh commands
    image: appleboy/drone-ssh
    settings:
      host: 122.51.158.110
      username: root
      port: 22
      password:
        from_secret: ssh_pwd
      script:
        - echo hello
        - echo world
  # 4.邮件通知
  - name: email-notice
    pull: if-not-exists
    image: drillster/drone-email
    settings:
      host: smtp.exmail.qq.com
      port: 465
      username: system@0moe.cn
      password: MjEcKARP3qAECSMS
      from: system@0moe.cn
    when:
      status: [failure, success]