name: deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./conf --file Dockerfile --tag latest --tag ${{ github.event.pull_request.head.sha }}:$(date +%s)
    - name: SSH-Compose
      uses: matiasnu/github-action-ssh-docker-compose@v2.0.1
      with:
        # Private SSH key used for logging into remote system.
        ssh_private_key: ${{ secrets.NOTE_PRIVATE_KEY }}
        # Remote host name.
        ssh_host: ${{ secrets.NOTE_HOST }}
        # Remote SSH port.
        ssh_user: ${{ secrets.NOTE_USER }}
        # Prefix for docker-compose containers.
        docker_compose_prefix: note
