name: deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_LOGIN_NAME }}
        password: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        file: ./conf/Dockerfile
        push: true
        tags: dawnsouther/0moe-note:latest
    - name: SSH-Compose
      uses: matiasnu/github-action-ssh-docker-compose@v2.0.1
      with:
        # Private SSH key used for logging into remote system.
        ssh_private_key: ${{ secrets.NOTE_PRIVATE_KEY }}
        # Remote host name.
        ssh_host: ${{ secrets.NOTE_HOST }}
        # Remote SSH port.
        ssh_user: ${{ secrets.NOTE_USER }}
        # Prefix for docker-compose containers.
        docker_compose_prefix: note
