name: deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_LOGIN_NAME }}
        password: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        file: ./conf/Dockerfile
        push: true
        tags: ghcr.io/dawnsouther/0moe-note:latest
    - uses: D3rHase/ssh-command-action@v0.2.2
      with:
        host: ${{ secrets.NOTE_HOST }} # Remote server address / ip - required
        user: ${{ secrets.NOTE_USER }} # Remote server user - required
        private_key: ${{secrets.NOTE_PRIVATE_KEY}} # Private ssh key registered on the remote server - required
        command: docker pull ghcr.io/dawnsouther/0moe-note:latest & docker-compose -f /0moe/docker-compose.yml up -d --force-recreate note
